/*
 * This file was automatically generated by EvoSuite
 */

package gnu.trove.impl.unmodifiable;

import org.junit.Test;
import static org.junit.Assert.*;
import gnu.trove.impl.unmodifiable.TUnmodifiableIntSet;
import gnu.trove.set.TIntSet;
import gnu.trove.set.hash.TIntHashSet;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;

public class TUnmodifiableIntSetEvoSuite_Branch {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.loadLogbackForEvoSuite(); 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.agent.InstrumentingAgent.initialize(); 
  } 

  @Before 
  public void initTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.deactivate(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.hashCode()I: root-Branch
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.<init>(Lgnu/trove/set/TIntSet;)V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      TIntHashSet tIntHashSet0 = new TIntHashSet();
      TUnmodifiableIntSet tUnmodifiableIntSet0 = new TUnmodifiableIntSet((TIntSet) tIntHashSet0);
      int int0 = tUnmodifiableIntSet0.hashCode();
      assertEquals(0, int0);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.equals(Ljava/lang/Object;)Z: I4 Branch 1 IF_ACMPEQ L58 - true
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.equals(Ljava/lang/Object;)Z: I9 Branch 2 IFEQ L58 - false
   */

  @Test
  public void test1()  throws Throwable  {
      TIntHashSet tIntHashSet0 = new TIntHashSet(59, 59);
      TUnmodifiableIntSet tUnmodifiableIntSet0 = new TUnmodifiableIntSet((TIntSet) tIntHashSet0);
      boolean boolean0 = tUnmodifiableIntSet0.equals((Object) tIntHashSet0);
      assertEquals(true, boolean0);
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.equals(Ljava/lang/Object;)Z: I4 Branch 1 IF_ACMPEQ L58 - false
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.equals(Ljava/lang/Object;)Z: I9 Branch 2 IFEQ L58 - true
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntSet.<init>(Lgnu/trove/set/TIntSet;)V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      TIntHashSet tIntHashSet0 = new TIntHashSet();
      TUnmodifiableIntSet tUnmodifiableIntSet0 = new TUnmodifiableIntSet((TIntSet) tIntHashSet0);
      boolean boolean0 = tUnmodifiableIntSet0.equals((Object) "");
      assertEquals(false, boolean0);
  }
}
