/*
 * This file was automatically generated by EvoSuite
 */

package gnu.trove.decorator;

import org.junit.Test;
import static org.junit.Assert.*;
import gnu.trove.decorator.TByteLongMapDecorator;
import gnu.trove.map.TByteLongMap;
import gnu.trove.map.hash.TByteLongHashMap;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PushbackInputStream;
import java.io.SequenceInputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.Properties.SandboxMode;
import org.evosuite.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

public class TByteLongMapDecoratorEvoSuite_Random {

  private static ExecutorService executor; 

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.agent.InstrumentingAgent.initialize(); 
    org.evosuite.Properties.SANDBOX_MODE = SandboxMode.RECOMMENDED; 
    Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    executor.shutdownNow(); 
    Sandbox.resetDefaultSecurityManager(); 
  } 

  @Before 
  public void initTestCase(){ 
    Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.agent.InstrumentingAgent.deactivate(); 
  } 


  @Test
  public void test0()  throws Throwable  {
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap();
      TByteLongHashMap tByteLongHashMap1 = new TByteLongHashMap((TByteLongMap) tByteLongHashMap0);
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap1);
      byte byte0 = (byte) (-1);
      Byte byte1 = new Byte(byte0);
      Long long0 = null;
      tByteLongMapDecorator0.put(byte1, long0);
      assertEquals(1, tByteLongHashMap1.size());
      assertFalse(tByteLongHashMap1.equals(tByteLongHashMap0));
  }

  @Test
  public void test1()  throws Throwable  {
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      Object object0 = null;
      tByteLongMapDecorator0.containsValue(object0);
      // Undeclared exception!
      try {
        tByteLongMapDecorator0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test2()  throws Throwable  {
      int int0 = 0;
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap(int0, int0);
      AbstractMap.SimpleEntry<TByteLongHashMap, Integer> abstractMap_SimpleEntry0 = new AbstractMap.SimpleEntry<TByteLongHashMap, Integer>(tByteLongHashMap0, (Integer) int0);
      abstractMap_SimpleEntry0.getKey();
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      HashMap<Integer, TByteLongHashMap> hashMap0 = new HashMap<Integer, TByteLongHashMap>();
      int int1 = (-116);
      PipedInputStream pipedInputStream0 = null;
      try {
        pipedInputStream0 = new PipedInputStream(int1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Pipe Size <= 0
         //
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      String string0 = "";
      String string1 = "";
      File file0 = new File(string1);
      // Undeclared exception!
      try {
        File.createTempFile(string0, string0, file0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Prefix string too short
         //
      }
  }

  @Test
  public void test4()  throws Throwable  {
      int int0 = 0;
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      PipedInputStream pipedInputStream0 = null;
      try {
        pipedInputStream0 = new PipedInputStream(int0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Pipe Size <= 0
         //
      }
  }

  @Test
  public void test5()  throws Throwable  {
      int int0 = (-1343);
      float float0 = 0.0F;
      byte byte0 = (byte)0;
      Long long0 = new Long((long) byte0);
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = byte0;
      byteArray0[1] = byte0;
      byteArray0[2] = byte0;
      byteArray0[3] = byte0;
      byte byte1 = (byte)124;
      byteArray0[4] = byte1;
      byteArray0[5] = byte0;
      long[] longArray0 = new long[10];
      longArray0[0] = (long) byteArray0[5];
      longArray0[1] = (long) byteArray0[2];
      longArray0[2] = (long) byteArray0[1];
      longArray0[3] = (long) byteArray0[2];
      longArray0[4] = (long) byteArray0[5];
      longArray0[5] = (long) long0;
      longArray0[6] = (long) byteArray0[4];
      longArray0[7] = (long) byte1;
      longArray0[8] = (long) byteArray0[0];
      longArray0[9] = (long) byteArray0[5];
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap(byteArray0, longArray0);
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap0);
      // Undeclared exception!
      try {
        tByteLongMapDecorator0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test6()  throws Throwable  {
      int int0 = 10;
      byte byte0 = (byte)110;
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      tByteLongMapDecorator0.values();
      // Undeclared exception!
      try {
        tByteLongMapDecorator0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test7()  throws Throwable  {
      byte[] byteArray0 = new byte[10];
      byte byte0 = (byte) (-127);
      byteArray0[0] = byte0;
      byte byte1 = (byte)39;
      byteArray0[1] = byte1;
      byte byte2 = (byte)19;
      byteArray0[2] = byte2;
      byte byte3 = (byte)0;
      byteArray0[3] = byte3;
      byte byte4 = (byte)59;
      byteArray0[4] = byte4;
      byte byte5 = (byte)12;
      byteArray0[5] = byte5;
      byte byte6 = (byte)0;
      byteArray0[6] = byte6;
      byte byte7 = (byte) (-1);
      byteArray0[7] = byte7;
      byte byte8 = (byte) (-26);
      byteArray0[8] = byte8;
      byte byte9 = (byte)99;
      byteArray0[9] = byte9;
      long[] longArray0 = new long[3];
      longArray0[0] = (long) byte5;
      longArray0[1] = (long) byteArray0[5];
      long long0 = 535L;
      longArray0[2] = long0;
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap(byteArray0, longArray0);
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap0);
      TByteLongMapDecorator tByteLongMapDecorator1 = new TByteLongMapDecorator();
  }

  @Test
  public void test8()  throws Throwable  {
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      byte byte0 = (byte)48;
      Byte byte1 = new Byte(byte0);
      long long0 = 589L;
      Long long1 = new Long(long0);
      // Undeclared exception!
      try {
        tByteLongMapDecorator0.put(byte1, long1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test9()  throws Throwable  {
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      byte byte0 = (byte)0;
      Byte byte1 = new Byte(byte0);
      Long long0 = new Long((long) byte0);
      // Undeclared exception!
      try {
        tByteLongMapDecorator0.put(byte1, long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test10()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            public void run() { 
        try {
          TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
          String string0 = "";
          FileOutputStream fileOutputStream0 = null;
          try {
            fileOutputStream0 = new FileOutputStream(string0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.io.FilePermission\" \"\" \"write\")
             // java.lang.Thread.getStackTrace(Thread.java:1567)
             // org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
             // java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
             // java.io.FileOutputStream.<init>(FileOutputStream.java:203)
             // java.io.FileOutputStream.<init>(FileOutputStream.java:104)
             // sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
             // sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
             // sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             // java.lang.reflect.Constructor.newInstance(Constructor.java:525)
             // org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
             // org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:144)
             // org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
             // org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
             // org.evosuite.testcase.TestRunnable.call(TestRunnable.java:1)
             // java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
             // java.util.concurrent.FutureTask.run(FutureTask.java:166)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
             // java.lang.Thread.run(Thread.java:722)
             //
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    }); 
    future.get(6000, TimeUnit.MILLISECONDS); 
  }

  @Test
  public void test11()  throws Throwable  {
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator();
      TByteLongMap tByteLongMap0 = tByteLongMapDecorator0.getMap();
      TByteLongMapDecorator tByteLongMapDecorator1 = new TByteLongMapDecorator(tByteLongMap0);
      tByteLongMapDecorator1.keySet();
      TByteLongMapDecorator tByteLongMapDecorator2 = new TByteLongMapDecorator();
      int int0 = 1470;
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap(int0);
      byte byte0 = (byte) (-1);
      Byte byte1 = new Byte(byte0);
      long long0 = 1L;
      Long long1 = new Long(long0);
      // Undeclared exception!
      try {
        tByteLongMapDecorator2.put(byte1, long1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test12()  throws Throwable  {
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap();
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap0);
      String string0 = "";
      // Undeclared exception!
      try {
        File.createTempFile(string0, string0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Prefix string too short
         //
      }
  }

  @Test
  public void test13()  throws Throwable  {
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap();
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap0);
      OutputStream outputStream0 = null;
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream((InputStream) pipedInputStream0, (InputStream) pipedInputStream0);
      int int0 = 1626;
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream((InputStream) sequenceInputStream0, int0);
      ObjectInputStream objectInputStream0 = null;
      try {
        objectInputStream0 = new ObjectInputStream((InputStream) pushbackInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
      }
  }

  @Test
  public void test14()  throws Throwable  {
      int int0 = 0;
      TByteLongHashMap tByteLongHashMap0 = new TByteLongHashMap(int0);
      TByteLongHashMap tByteLongHashMap1 = new TByteLongHashMap((TByteLongMap) tByteLongHashMap0);
      TByteLongMapDecorator tByteLongMapDecorator0 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap1);
      int int1 = 1322;
      byte byte0 = (byte)0;
      long long0 = 1L;
      TByteLongHashMap tByteLongHashMap2 = new TByteLongHashMap(int1, (float) int0, byte0, long0);
      tByteLongMapDecorator0.remove((Object) tByteLongHashMap2);
      TByteLongMapDecorator tByteLongMapDecorator1 = new TByteLongMapDecorator((TByteLongMap) tByteLongHashMap0);
      byte byte1 = (byte)0;
      Byte byte2 = new Byte(byte1);
      tByteLongHashMap0.valueCollection();
      long long1 = 1736L;
      Long long2 = new Long(long1);
      tByteLongMapDecorator0.put(byte2, long2);
      String string0 = "";
      URI uRI0 = null;
      try {
        uRI0 = new URI(string0, string0, string0, string0, string0);
        fail("Expecting exception: URISyntaxException");
      
      } catch(URISyntaxException e) {
         //
         // Expected scheme name at index 0: ://?#
         //
      }
  }
}
