/*
 * This file was automatically generated by EvoSuite
 */

package gnu.trove.impl.unmodifiable;

import org.junit.Test;
import static org.junit.Assert.*;
import gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap;
import gnu.trove.impl.unmodifiable.TUnmodifiableShortSet;
import gnu.trove.map.TShortObjectMap;
import gnu.trove.map.hash.TShortObjectHashMap;
import gnu.trove.procedure.TObjectProcedure;
import gnu.trove.procedure.TShortProcedure;
import gnu.trove.procedure.array.ToObjectArrayProceedure;
import java.util.Collection;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;

public class TUnmodifiableShortObjectMapEvoSuite_DefUse {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.loadLogbackForEvoSuite(); 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.agent.InstrumentingAgent.initialize(); 
  } 

  @Before 
  public void initTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.deactivate(); 
  } 


  //Test case number: 0
  /*
   * 6 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 48 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in isEmpty()Z.4 root-Branch Line 59
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 9 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in isEmpty()Z.3 root-Branch Line 59
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.isEmpty()Z: root-Branch
   * 4 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TShortObjectMap;)V
	Use 6 for Parameter-Variable "<init>(Lgnu/trove/map/TShortObjectMap;)V_LV_1" in <init>(Lgnu/trove/map/TShortObjectMap;)V.16 root-Branch Line 53
   * 5 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TShortObjectMap;)V
	Use 7 for Parameter-Variable "<init>(Lgnu/trove/map/TShortObjectMap;)V_LV_1" in <init>(Lgnu/trove/map/TShortObjectMap;)V.27 Branch 1t Line 55
   * 6 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.<init>(Lgnu/trove/map/TShortObjectMap;)V: I17 Branch 1 IFNONNULL L53 - true
   */

  @Test
  public void test0()  throws Throwable  {
      TShortObjectHashMap<Short> tShortObjectHashMap0 = new TShortObjectHashMap<Short>(1338);
      TUnmodifiableShortObjectMap<Short> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Short>((TShortObjectMap<Short>) tShortObjectHashMap0);
      boolean boolean0 = tUnmodifiableShortObjectMap0.isEmpty();
      assertEquals(true, boolean0);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 44 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in containsKey(S)Z.5 root-Branch Line 60
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 10 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in containsKey(S)Z.3 root-Branch Line 60
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method containsKey(S)Z
	Use 11 for Parameter-Variable "containsKey(S)Z_LV_1" in containsKey(S)Z.4 root-Branch Line 60
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.containsKey(S)Z: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      TShortObjectHashMap<Short> tShortObjectHashMap0 = new TShortObjectHashMap<Short>();
      TUnmodifiableShortObjectMap<Short> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Short>((TShortObjectMap<Short>) tShortObjectHashMap0);
      boolean boolean0 = tUnmodifiableShortObjectMap0.containsKey((short) (-984));
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 12 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in containsValue(Ljava/lang/Object;)Z.3 root-Branch Line 61
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 47 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in containsValue(Ljava/lang/Object;)Z.5 root-Branch Line 61
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method containsValue(Ljava/lang/Object;)Z
	Use 13 for Parameter-Variable "containsValue(Ljava/lang/Object;)Z_LV_1" in containsValue(Ljava/lang/Object;)Z.4 root-Branch Line 61
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.containsValue(Ljava/lang/Object;)Z: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-1950));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      boolean boolean0 = tUnmodifiableShortObjectMap0.containsValue((Object) null);
      assertEquals(false, boolean0);
  }

  //Test case number: 3
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 14 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in get(S)Ljava/lang/Object;.3 root-Branch Line 62
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 57 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in get(S)Ljava/lang/Object;.5 root-Branch Line 62
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method get(S)Ljava/lang/Object;
	Use 15 for Parameter-Variable "get(S)Ljava/lang/Object;_LV_1" in get(S)Ljava/lang/Object;.4 root-Branch Line 62
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.get(S)Ljava/lang/Object;: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      TShortObjectHashMap<Short> tShortObjectHashMap0 = new TShortObjectHashMap<Short>();
      TShortObjectHashMap<Object> tShortObjectHashMap1 = new TShortObjectHashMap<Object>((TShortObjectMap<?>) tShortObjectHashMap0);
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap1);
      Object object0 = tUnmodifiableShortObjectMap0.get((short) (-984));
      assertNull(object0);
  }

  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 43 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keys()[S.4 root-Branch Line 78
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 19 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keys()[S.3 root-Branch Line 78
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.keys()[S: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      TShortObjectHashMap<Object> tShortObjectHashMap0 = new TShortObjectHashMap<Object>();
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap0);
      short[] shortArray0 = tUnmodifiableShortObjectMap0.keys();
      assertNotNull(shortArray0);
  }

  //Test case number: 5
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 20 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keys([S)[S.3 root-Branch Line 79
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 58 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keys([S)[S.5 root-Branch Line 79
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method keys([S)[S
	Use 21 for Parameter-Variable "keys([S)[S_LV_1" in keys([S)[S.4 root-Branch Line 79
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.keys([S)[S: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      TShortObjectHashMap<Object> tShortObjectHashMap0 = new TShortObjectHashMap<Object>();
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap0);
      short[] shortArray0 = tUnmodifiableShortObjectMap0.keys(tShortObjectHashMap0._set);
      assertNotNull(shortArray0);
  }

  //Test case number: 6
  /*
   * 13 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 49 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in values()[Ljava/lang/Object;.4 root-Branch Line 86
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 25 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in values()[Ljava/lang/Object;.3 root-Branch Line 86
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.values()[Ljava/lang/Object;: root-Branch
   * 4 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 33 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in getNoEntryKey()S.3 root-Branch Line 92
   * 5 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 40 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in getNoEntryKey()S.4 root-Branch Line 92
   * 6 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 8 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in size()I.3 root-Branch Line 58
   * 7 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 54 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z.5 root-Branch Line 101
   * 8 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 50 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in size()I.4 root-Branch Line 58
   * 9 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 38 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z.3 root-Branch Line 101
   * 10 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z
	Use 39 for Parameter-Variable "forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z_LV_1" in forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z.4 root-Branch Line 101
   * 11 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.getNoEntryKey()S: root-Branch
   * 12 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.forEachEntry(Lgnu/trove/procedure/TShortObjectProcedure;)Z: root-Branch
   * 13 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.size()I: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-1950));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      TShortObjectHashMap<Object> tShortObjectHashMap1 = new TShortObjectHashMap<Object>((TShortObjectMap<?>) tUnmodifiableShortObjectMap0);
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap1 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap1);
      Object[] objectArray0 = tUnmodifiableShortObjectMap1.values();
      assertNotNull(objectArray0);
  }

  //Test case number: 7
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 26 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in values([Ljava/lang/Object;)[Ljava/lang/Object;.3 root-Branch Line 87
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 60 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in values([Ljava/lang/Object;)[Ljava/lang/Object;.5 root-Branch Line 87
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method values([Ljava/lang/Object;)[Ljava/lang/Object;
	Use 27 for Parameter-Variable "values([Ljava/lang/Object;)[Ljava/lang/Object;_LV_1" in values([Ljava/lang/Object;)[Ljava/lang/Object;.4 root-Branch Line 87
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.values([Ljava/lang/Object;)[Ljava/lang/Object;: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      TShortObjectHashMap<String> tShortObjectHashMap0 = new TShortObjectHashMap<String>((-1950));
      TUnmodifiableShortObjectMap<String> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<String>((TShortObjectMap<String>) tShortObjectHashMap0);
      String[] stringArray0 = new String[1];
      String[] stringArray1 = tUnmodifiableShortObjectMap0.values(stringArray0);
      assertSame(stringArray0, stringArray1);
  }

  //Test case number: 8
  /*
   * 6 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 29 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in equals(Ljava/lang/Object;)Z.6 Branch 4f Line 89
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 52 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in equals(Ljava/lang/Object;)Z.8 Branch 4f Line 89
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method equals(Ljava/lang/Object;)Z
	Use 30 for Parameter-Variable "equals(Ljava/lang/Object;)Z_LV_1" in equals(Ljava/lang/Object;)Z.7 Branch 4f Line 89
   * 4 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method equals(Ljava/lang/Object;)Z
	Use 28 for Parameter-Variable "equals(Ljava/lang/Object;)Z_LV_1" in equals(Ljava/lang/Object;)Z.2 root-Branch Line 89
   * 5 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.equals(Ljava/lang/Object;)Z: I4 Branch 4 IF_ACMPEQ L89 - false
   * 6 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.equals(Ljava/lang/Object;)Z: I9 Branch 5 IFEQ L89 - true
   */

  @Test
  public void test8()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-17), (float) (-17), (short) (-5));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      boolean boolean0 = tUnmodifiableShortObjectMap0.equals((Object) "{}");
      assertEquals(false, boolean0);
  }

  //Test case number: 9
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 31 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in hashCode()I.3 root-Branch Line 90
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 55 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in hashCode()I.4 root-Branch Line 90
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.hashCode()I: root-Branch
   */

  @Test
  public void test9()  throws Throwable  {
      TShortObjectHashMap<Short> tShortObjectHashMap0 = new TShortObjectHashMap<Short>();
      TShortObjectHashMap<Object> tShortObjectHashMap1 = new TShortObjectHashMap<Object>((TShortObjectMap<?>) tShortObjectHashMap0);
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap1);
      int int0 = tUnmodifiableShortObjectMap0.hashCode();
      assertEquals(0, int0);
  }

  //Test case number: 10
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 41 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in toString()Ljava/lang/String;.4 root-Branch Line 91
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 32 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in toString()Ljava/lang/String;.3 root-Branch Line 91
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.toString()Ljava/lang/String;: root-Branch
   */

  @Test
  public void test10()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-17), (float) (-17), (short) (-5));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      String string0 = tUnmodifiableShortObjectMap0.toString();
      assertEquals("{}", string0);
  }

  //Test case number: 11
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 42 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z.5 root-Branch Line 95
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 34 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z.3 root-Branch Line 95
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z
	Use 35 for Parameter-Variable "forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z_LV_1" in forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z.4 root-Branch Line 95
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.forEachKey(Lgnu/trove/procedure/TShortProcedure;)Z: root-Branch
   */

  @Test
  public void test11()  throws Throwable  {
      TShortObjectHashMap<Short> tShortObjectHashMap0 = new TShortObjectHashMap<Short>();
      TShortObjectHashMap<Object> tShortObjectHashMap1 = new TShortObjectHashMap<Object>((TShortObjectMap<?>) tShortObjectHashMap0);
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap1);
      boolean boolean0 = tUnmodifiableShortObjectMap0.forEachKey((TShortProcedure) null);
      assertEquals(true, boolean0);
  }

  //Test case number: 12
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 61 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z.5 root-Branch Line 98
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 36 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z.3 root-Branch Line 98
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z
	Use 37 for Parameter-Variable "forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z_LV_1" in forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z.4 root-Branch Line 98
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.forEachValue(Lgnu/trove/procedure/TObjectProcedure;)Z: root-Branch
   */

  @Test
  public void test12()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-1950));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      Object[] objectArray0 = new Object[1];
      ToObjectArrayProceedure<Object> toObjectArrayProceedure0 = new ToObjectArrayProceedure<Object>(objectArray0);
      boolean boolean0 = tUnmodifiableShortObjectMap0.forEachValue((TObjectProcedure<? super Integer>) toObjectArrayProceedure0);
      assertEquals(true, boolean0);
  }

  //Test case number: 13
  /*
   * 7 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 5 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in keySet()Lgnu/trove/set/TShortSet;.12 Branch 2f Line 75
	Use 16 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in keySet()Lgnu/trove/set/TShortSet;.3 root-Branch Line 74
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.keySet()Lgnu/trove/set/TShortSet;: I4 Branch 2 IFNONNULL L74 - true
   * 3 INTRA_METHOD-Definition-Use-Pair
	Definition 5 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in keySet()Lgnu/trove/set/TShortSet;.12 Branch 2f Line 75
	Use 18 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in keySet()Lgnu/trove/set/TShortSet;.16 root-Branch Line 76
   * 4 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 56 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keySet()Lgnu/trove/set/TShortSet;.10 Branch 2f Line 75
   * 5 INTRA_CLASS-Definition-Use-Pair
	Definition 2 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in <init>(Lgnu/trove/map/TShortObjectMap;)V.8 root-Branch Line 70
	Use 16 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.keySet" in keySet()Lgnu/trove/set/TShortSet;.3 root-Branch Line 74
   * 6 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 17 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in keySet()Lgnu/trove/set/TShortSet;.9 Branch 2f Line 75
   * 7 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.keySet()Lgnu/trove/set/TShortSet;: I4 Branch 2 IFNONNULL L74 - false
   */

  @Test
  public void test13()  throws Throwable  {
      TShortObjectHashMap<Object> tShortObjectHashMap0 = new TShortObjectHashMap<Object>();
      TUnmodifiableShortObjectMap<Object> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Object>((TShortObjectMap<Object>) tShortObjectHashMap0);
      TUnmodifiableShortSet tUnmodifiableShortSet0 = (TUnmodifiableShortSet)tUnmodifiableShortObjectMap0.keySet();
      assertNotNull(tUnmodifiableShortSet0);
      
      TUnmodifiableShortSet tUnmodifiableShortSet1 = (TUnmodifiableShortSet)tUnmodifiableShortObjectMap0.keySet();
      assertSame(tUnmodifiableShortSet1, tUnmodifiableShortSet0);
  }

  //Test case number: 14
  /*
   * 9 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 6 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in valueCollection()Ljava/util/Collection;.12 Branch 3f Line 83
	Use 22 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in valueCollection()Ljava/util/Collection;.3 root-Branch Line 82
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.valueCollection()Ljava/util/Collection;: I4 Branch 3 IFNONNULL L82 - true
   * 3 INTRA_CLASS-Definition-Use-Pair
	Definition 3 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in <init>(Lgnu/trove/map/TShortObjectMap;)V.13 root-Branch Line 71
	Use 22 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in valueCollection()Ljava/util/Collection;.3 root-Branch Line 82
   * 4 INTRA_METHOD-Definition-Use-Pair
	Definition 6 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in valueCollection()Ljava/util/Collection;.12 Branch 3f Line 83
	Use 24 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.values" in valueCollection()Ljava/util/Collection;.16 root-Branch Line 84
   * 5 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 46 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in valueCollection()Ljava/util/Collection;.10 Branch 3f Line 83
   * 6 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in <init>(Lgnu/trove/map/TShortObjectMap;)V.28 Branch 1t Line 55
	Use 23 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableShortObjectMap.m" in valueCollection()Ljava/util/Collection;.9 Branch 3f Line 83
   * 7 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TShortObjectMap;)V
	Use 6 for Parameter-Variable "<init>(Lgnu/trove/map/TShortObjectMap;)V_LV_1" in <init>(Lgnu/trove/map/TShortObjectMap;)V.16 root-Branch Line 53
   * 8 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TShortObjectMap;)V
	Use 7 for Parameter-Variable "<init>(Lgnu/trove/map/TShortObjectMap;)V_LV_1" in <init>(Lgnu/trove/map/TShortObjectMap;)V.27 Branch 1t Line 55
   * 9 gnu.trove.impl.unmodifiable.TUnmodifiableShortObjectMap.valueCollection()Ljava/util/Collection;: I4 Branch 3 IFNONNULL L82 - false
   */

  @Test
  public void test14()  throws Throwable  {
      TShortObjectHashMap<Integer> tShortObjectHashMap0 = new TShortObjectHashMap<Integer>((-1950));
      TUnmodifiableShortObjectMap<Integer> tUnmodifiableShortObjectMap0 = new TUnmodifiableShortObjectMap<Integer>((TShortObjectMap<Integer>) tShortObjectHashMap0);
      Collection<Integer> collection0 = tUnmodifiableShortObjectMap0.valueCollection();
      assertNotNull(collection0);
      
      Collection<Integer> collection1 = tUnmodifiableShortObjectMap0.valueCollection();
      assertSame(collection1, collection0);
  }
}
