/*
 * This file was automatically generated by EvoSuite
 */

package gnu.trove.impl.unmodifiable;

import org.junit.Test;
import static org.junit.Assert.*;
import gnu.trove.impl.unmodifiable.TUnmodifiableRandomAccessByteList;
import gnu.trove.list.TByteList;
import gnu.trove.list.array.TByteArrayList;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;

public class TUnmodifiableRandomAccessByteListEvoSuite_DefUse {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.loadLogbackForEvoSuite(); 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.agent.InstrumentingAgent.initialize(); 
  } 

  @Before 
  public void initTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.deactivate(); 
  } 


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method subList(II)Lgnu/trove/list/TByteList;
	Use 2 for Parameter-Variable "subList(II)Lgnu/trove/list/TByteList;_LV_1" in subList(II)Lgnu/trove/list/TByteList;.6 root-Branch Line 62
   * 2 PARAMETER-Definition-Use-Pair
	Parameter-Definition 2 for method subList(II)Lgnu/trove/list/TByteList;
	Use 3 for Parameter-Variable "subList(II)Lgnu/trove/list/TByteList;_LV_2" in subList(II)Lgnu/trove/list/TByteList;.7 root-Branch Line 62
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableRandomAccessByteList.subList(II)Lgnu/trove/list/TByteList;: root-Branch
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableRandomAccessByteList.<init>(Lgnu/trove/list/TByteList;)V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      TByteArrayList tByteArrayList0 = TByteArrayList.wrap(byteArray0);
      TUnmodifiableRandomAccessByteList tUnmodifiableRandomAccessByteList0 = new TUnmodifiableRandomAccessByteList((TByteList) tByteArrayList0);
      // Undeclared exception!
      try {
        tUnmodifiableRandomAccessByteList0.subList(1, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // end index 0 greater than begin index 1
         //
      }
  }
}
