/*
 * This file was automatically generated by EvoSuite
 */

package gnu.trove.impl.unmodifiable;

import org.junit.Test;
import static org.junit.Assert.*;
import gnu.trove.impl.unmodifiable.TUnmodifiableCharCollection;
import gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap;
import gnu.trove.impl.unmodifiable.TUnmodifiableIntSet;
import gnu.trove.map.TIntCharMap;
import gnu.trove.map.hash.TIntCharHashMap;
import gnu.trove.procedure.TCharProcedure;
import gnu.trove.procedure.TIntCharProcedure;
import gnu.trove.procedure.TIntProcedure;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;

public class TUnmodifiableIntCharMapEvoSuite_DefUse {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.loadLogbackForEvoSuite(); 
    org.evosuite.Properties.REPLACE_CALLS = true; 
    org.evosuite.agent.InstrumentingAgent.initialize(); 
  } 

  @Before 
  public void initTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    org.evosuite.agent.InstrumentingAgent.deactivate(); 
  } 


  //Test case number: 0
  /*
   * 6 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 42 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in size()I.4 root-Branch Line 63
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 8 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in size()I.3 root-Branch Line 63
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.size()I: root-Branch
   * 4 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TIntCharMap;)V
	Use 6 for Parameter-Variable "<init>(Lgnu/trove/map/TIntCharMap;)V_LV_1" in <init>(Lgnu/trove/map/TIntCharMap;)V.16 root-Branch Line 58
   * 5 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TIntCharMap;)V
	Use 7 for Parameter-Variable "<init>(Lgnu/trove/map/TIntCharMap;)V_LV_1" in <init>(Lgnu/trove/map/TIntCharMap;)V.27 Branch 1t Line 60
   * 6 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.<init>(Lgnu/trove/map/TIntCharMap;)V: I17 Branch 1 IFNONNULL L58 - true
   */

  @Test
  public void test0()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(22, (float) 22, 22, 'i');
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      int int0 = tUnmodifiableIntCharMap0.size();
      assertEquals(0, int0);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 44 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in isEmpty()Z.4 root-Branch Line 64
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 9 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in isEmpty()Z.3 root-Branch Line 64
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.isEmpty()Z: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.isEmpty();
      assertEquals(true, boolean0);
  }

  //Test case number: 2
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 53 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in containsKey(I)Z.5 root-Branch Line 65
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 10 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in containsKey(I)Z.3 root-Branch Line 65
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method containsKey(I)Z
	Use 11 for Parameter-Variable "containsKey(I)Z_LV_1" in containsKey(I)Z.4 root-Branch Line 65
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.containsKey(I)Z: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.containsKey(0);
      assertEquals(false, boolean0);
  }

  //Test case number: 3
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 48 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in containsValue(C)Z.5 root-Branch Line 66
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 12 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in containsValue(C)Z.3 root-Branch Line 66
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method containsValue(C)Z
	Use 13 for Parameter-Variable "containsValue(C)Z_LV_1" in containsValue(C)Z.4 root-Branch Line 66
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.containsValue(C)Z: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[16];
      char[] charArray0 = new char[2];
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(intArray0, charArray0);
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.containsValue('^');
      assertEquals(false, boolean0);
  }

  //Test case number: 4
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 52 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in get(I)C.5 root-Branch Line 67
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 14 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in get(I)C.3 root-Branch Line 67
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method get(I)C
	Use 15 for Parameter-Variable "get(I)C_LV_1" in get(I)C.4 root-Branch Line 67
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.get(I)C: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      char char0 = tUnmodifiableIntCharMap0.get(220);
      assertEquals('\u0000', char0);
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 19 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keys()[I.3 root-Branch Line 83
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 43 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keys()[I.4 root-Branch Line 83
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.keys()[I: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      int[] intArray0 = tUnmodifiableIntCharMap0.keys();
      assertNotNull(intArray0);
  }

  //Test case number: 6
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 20 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keys([I)[I.3 root-Branch Line 84
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 46 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keys([I)[I.5 root-Branch Line 84
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method keys([I)[I
	Use 21 for Parameter-Variable "keys([I)[I_LV_1" in keys([I)[I.4 root-Branch Line 84
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.keys([I)[I: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      int[] intArray0 = tUnmodifiableIntCharMap0.keys(tIntCharHashMap0._set);
      assertNotNull(intArray0);
  }

  //Test case number: 7
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 25 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in values()[C.3 root-Branch Line 91
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 50 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in values()[C.4 root-Branch Line 91
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.values()[C: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      int[] intArray0 = new int[16];
      char[] charArray0 = new char[2];
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(intArray0, charArray0);
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      char[] charArray1 = tUnmodifiableIntCharMap0.values();
      assertFalse(charArray1.equals(charArray0));
  }

  //Test case number: 8
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 62 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in values([C)[C.5 root-Branch Line 92
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 26 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in values([C)[C.3 root-Branch Line 92
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method values([C)[C
	Use 27 for Parameter-Variable "values([C)[C_LV_1" in values([C)[C.4 root-Branch Line 92
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.values([C)[C: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
      int[] intArray0 = new int[4];
      char[] charArray0 = new char[5];
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(intArray0, charArray0);
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      char[] charArray1 = tUnmodifiableIntCharMap0.values(charArray0);
      assertSame(charArray0, charArray1);
  }

  //Test case number: 9
  /*
   * 6 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 55 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in equals(Ljava/lang/Object;)Z.8 Branch 4f Line 94
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 29 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in equals(Ljava/lang/Object;)Z.6 Branch 4f Line 94
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method equals(Ljava/lang/Object;)Z
	Use 28 for Parameter-Variable "equals(Ljava/lang/Object;)Z_LV_1" in equals(Ljava/lang/Object;)Z.2 root-Branch Line 94
   * 4 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method equals(Ljava/lang/Object;)Z
	Use 30 for Parameter-Variable "equals(Ljava/lang/Object;)Z_LV_1" in equals(Ljava/lang/Object;)Z.7 Branch 4f Line 94
   * 5 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.equals(Ljava/lang/Object;)Z: I4 Branch 4 IF_ACMPEQ L94 - false
   * 6 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.equals(Ljava/lang/Object;)Z: I9 Branch 5 IFEQ L94 - true
   */

  @Test
  public void test9()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(22, (float) 22, 22, 'i');
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.equals((Object) "");
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 60 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in hashCode()I.4 root-Branch Line 95
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 31 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in hashCode()I.3 root-Branch Line 95
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.hashCode()I: root-Branch
   */

  @Test
  public void test10()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      int int0 = tUnmodifiableIntCharMap0.hashCode();
      assertEquals(0, int0);
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 59 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in toString()Ljava/lang/String;.4 root-Branch Line 96
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 32 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in toString()Ljava/lang/String;.3 root-Branch Line 96
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.toString()Ljava/lang/String;: root-Branch
   */

  @Test
  public void test11()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(22, (float) 22, 22, 'i');
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      String string0 = tUnmodifiableIntCharMap0.toString();
      assertEquals("{}", string0);
  }

  //Test case number: 12
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 49 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in getNoEntryKey()I.4 root-Branch Line 97
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 33 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in getNoEntryKey()I.3 root-Branch Line 97
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.getNoEntryKey()I: root-Branch
   */

  @Test
  public void test12()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      int int0 = tUnmodifiableIntCharMap0.getNoEntryKey();
      assertEquals(0, int0);
  }

  //Test case number: 13
  /*
   * 3 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 41 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in getNoEntryValue()C.4 root-Branch Line 98
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 34 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in getNoEntryValue()C.3 root-Branch Line 98
   * 3 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.getNoEntryValue()C: root-Branch
   */

  @Test
  public void test13()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(22, (float) 22, 22, 'i');
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      char char0 = tUnmodifiableIntCharMap0.getNoEntryValue();
      assertEquals('i', char0);
  }

  //Test case number: 14
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 35 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z.3 root-Branch Line 101
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 63 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z.5 root-Branch Line 101
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z
	Use 36 for Parameter-Variable "forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z_LV_1" in forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z.4 root-Branch Line 101
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.forEachKey(Lgnu/trove/procedure/TIntProcedure;)Z: root-Branch
   */

  @Test
  public void test14()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(1337);
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.forEachKey((TIntProcedure) null);
      assertEquals(true, boolean0);
  }

  //Test case number: 15
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 37 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z.3 root-Branch Line 104
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 45 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z.5 root-Branch Line 104
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z
	Use 38 for Parameter-Variable "forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z_LV_1" in forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z.4 root-Branch Line 104
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.forEachValue(Lgnu/trove/procedure/TCharProcedure;)Z: root-Branch
   */

  @Test
  public void test15()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.forEachValue((TCharProcedure) null);
      assertEquals(true, boolean0);
  }

  //Test case number: 16
  /*
   * 4 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 58 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z.5 root-Branch Line 107
   * 2 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 39 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z.3 root-Branch Line 107
   * 3 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z
	Use 40 for Parameter-Variable "forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z_LV_1" in forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z.4 root-Branch Line 107
   * 4 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.forEachEntry(Lgnu/trove/procedure/TIntCharProcedure;)Z: root-Branch
   */

  @Test
  public void test16()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(1337);
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      boolean boolean0 = tUnmodifiableIntCharMap0.forEachEntry((TIntCharProcedure) null);
      assertEquals(true, boolean0);
  }

  //Test case number: 17
  /*
   * 7 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 5 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in keySet()Lgnu/trove/set/TIntSet;.12 Branch 2f Line 80
	Use 16 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in keySet()Lgnu/trove/set/TIntSet;.3 root-Branch Line 79
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.keySet()Lgnu/trove/set/TIntSet;: I4 Branch 2 IFNONNULL L79 - true
   * 3 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 47 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keySet()Lgnu/trove/set/TIntSet;.10 Branch 2f Line 80
   * 4 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 17 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in keySet()Lgnu/trove/set/TIntSet;.9 Branch 2f Line 80
   * 5 INTRA_CLASS-Definition-Use-Pair
	Definition 2 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in <init>(Lgnu/trove/map/TIntCharMap;)V.8 root-Branch Line 75
	Use 16 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in keySet()Lgnu/trove/set/TIntSet;.3 root-Branch Line 79
   * 6 INTRA_METHOD-Definition-Use-Pair
	Definition 5 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in keySet()Lgnu/trove/set/TIntSet;.12 Branch 2f Line 80
	Use 18 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.keySet" in keySet()Lgnu/trove/set/TIntSet;.16 root-Branch Line 81
   * 7 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.keySet()Lgnu/trove/set/TIntSet;: I4 Branch 2 IFNONNULL L79 - false
   */

  @Test
  public void test17()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap(22, (float) 22, 22, 'i');
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      TUnmodifiableIntSet tUnmodifiableIntSet0 = (TUnmodifiableIntSet)tUnmodifiableIntCharMap0.keySet();
      assertNotNull(tUnmodifiableIntSet0);
      
      TUnmodifiableIntSet tUnmodifiableIntSet1 = (TUnmodifiableIntSet)tUnmodifiableIntCharMap0.keySet();
      assertSame(tUnmodifiableIntSet1, tUnmodifiableIntSet0);
  }

  //Test case number: 18
  /*
   * 9 covered goals:
   * 1 INTRA_CLASS-Definition-Use-Pair
	Definition 6 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in valueCollection()Lgnu/trove/TCharCollection;.12 Branch 3f Line 88
	Use 22 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in valueCollection()Lgnu/trove/TCharCollection;.3 root-Branch Line 87
   * 2 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.valueCollection()Lgnu/trove/TCharCollection;: I4 Branch 3 IFNONNULL L87 - true
   * 3 INTRA_METHOD-Definition-Use-Pair
	Definition 6 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in valueCollection()Lgnu/trove/TCharCollection;.12 Branch 3f Line 88
	Use 24 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in valueCollection()Lgnu/trove/TCharCollection;.16 root-Branch Line 89
   * 4 INTRA_CLASS-Definition-Use-Pair
	Definition 3 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in <init>(Lgnu/trove/map/TIntCharMap;)V.13 root-Branch Line 76
	Use 22 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.values" in valueCollection()Lgnu/trove/TCharCollection;.3 root-Branch Line 87
   * 5 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 23 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in valueCollection()Lgnu/trove/TCharCollection;.9 Branch 3f Line 88
   * 6 INTRA_CLASS-Definition-Use-Pair
	Definition 4 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in <init>(Lgnu/trove/map/TIntCharMap;)V.28 Branch 1t Line 60
	Use 56 for Field-Variable "gnu/trove/impl/unmodifiable/TUnmodifiableIntCharMap.m" in valueCollection()Lgnu/trove/TCharCollection;.10 Branch 3f Line 88
   * 7 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TIntCharMap;)V
	Use 6 for Parameter-Variable "<init>(Lgnu/trove/map/TIntCharMap;)V_LV_1" in <init>(Lgnu/trove/map/TIntCharMap;)V.16 root-Branch Line 58
   * 8 PARAMETER-Definition-Use-Pair
	Parameter-Definition 1 for method <init>(Lgnu/trove/map/TIntCharMap;)V
	Use 7 for Parameter-Variable "<init>(Lgnu/trove/map/TIntCharMap;)V_LV_1" in <init>(Lgnu/trove/map/TIntCharMap;)V.27 Branch 1t Line 60
   * 9 gnu.trove.impl.unmodifiable.TUnmodifiableIntCharMap.valueCollection()Lgnu/trove/TCharCollection;: I4 Branch 3 IFNONNULL L87 - false
   */

  @Test
  public void test18()  throws Throwable  {
      TIntCharHashMap tIntCharHashMap0 = new TIntCharHashMap();
      TUnmodifiableIntCharMap tUnmodifiableIntCharMap0 = new TUnmodifiableIntCharMap((TIntCharMap) tIntCharHashMap0);
      TUnmodifiableCharCollection tUnmodifiableCharCollection0 = (TUnmodifiableCharCollection)tUnmodifiableIntCharMap0.valueCollection();
      assertNotNull(tUnmodifiableCharCollection0);
      
      TUnmodifiableCharCollection tUnmodifiableCharCollection1 = (TUnmodifiableCharCollection)tUnmodifiableIntCharMap0.valueCollection();
      assertSame(tUnmodifiableCharCollection1, tUnmodifiableCharCollection0);
  }
}
